disable H2 server due to startup failures in AWS
org.h2.jdbc.JdbcSQLNonTransientException: IO Exception: "java.net.UnknownHostException: 42c78b4dead8: 42c78b4dead8: Name or service not known" [90028-200]

https://stackoverflow.com/questions/16610483/h2-database-will-not-run-on-opensuse-12-2