Only build Spring Boot JAR (see https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/htmlsingle/#packaging-executable.and-plain-archives) because otherwise the Docker build will fail due to multiple JAR files in the build directory:
"When using COPY with more than one source file, the destination must be a directory and end with a /
 Error: Process completed with exit code 1."